# Alternative GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug)
  GLFW_config = debug
  AlphaProject_config = debug

else
  $(error "invalid configuration $(config)")
endif

PROJECTS := GLFW AlphaProject

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

GLFW:
ifneq (,$(GLFW_config))
	@echo "==== Building GLFW ($(GLFW_config)) ===="
	@${MAKE} --no-print-directory -C AlphaProject/vendor/GLFW -f Makefile config=$(GLFW_config)
endif

AlphaProject: GLFW
ifneq (,$(AlphaProject_config))
	@echo "==== Building AlphaProject ($(AlphaProject_config)) ===="
	@${MAKE} --no-print-directory -C AlphaProject -f Makefile config=$(AlphaProject_config)
endif

clean:
	@${MAKE} --no-print-directory -C AlphaProject/vendor/GLFW -f Makefile clean
	@${MAKE} --no-print-directory -C AlphaProject -f Makefile clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   GLFW"
	@echo "   AlphaProject"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"