@startuml arch_proyecto_alpha

class User {
    - int id
    - string nombre
    - string password

    + User(int id, string nombre, string password)
    + \~User()
    + int getId()
    + string getNombre()
    + string getHashPassword()
}

class UserManager {
    - int sizeUsers
    - int currentPosition
    - User[] users

    + UserManager()
    + \~UserManager()
    + bool newUser(string nombre, string password)
    + User getUser(int id)
    - void growUsers()
}

class WhackAMole {
    - int boardSize
    - vector<vector<int>> board
    - map<int, int> userPuntuation

    + WhackAMole(int boardSize)
    + void setBoardSize(int boardSize)
    + int getBoardSideSize()
    + string getBoard()
    + bool setNewUserPuntuation(int userId)
    + int getNewMolePosition()
    + bool setUserPuntuation(int userId)
}

User "Is use by" --> UserManager 

@enduml
